# Generated by Django 4.2.30 on 2026-05-21 11:51

from django.db import migrations, models
import pendulum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=pendulum.now)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GeneralInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('service', models.CharField(blank=True, help_text='Service the person is interested in', max_length=200)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=pendulum.now)),
            ],
            options={
                'verbose_name': 'General Inquiry',
                'verbose_name_plural': 'General Inquiries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
