# Generated by Django 6.0.5 on 2026-05-20 22:56

import pendulum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=pendulum.now),
        ),
    ]
