# Generated by Django 4.2.30 on 2026-05-21 07:05

from django.db import migrations, models
import domains.listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to=domains.listings.models.listing_photo_path),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to=domains.listings.models.listing_photo_path),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to=domains.listings.models.listing_photo_path),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to=domains.listings.models.listing_photo_path),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to=domains.listings.models.listing_photo_path),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to=domains.listings.models.listing_photo_path),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to=domains.listings.models.listing_photo_path),
        ),
    ]
