# Generated by Django 4.2.30 on 2026-05-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_photo_1_alter_listing_photo_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='land_area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For land listings: total plot area in sqft', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('property_sale', 'Completed Property for Sale'), ('land_sale', 'Land for Sale')], default='property_sale', max_length=20),
        ),
    ]
