# Generated by Django 4.2.30 on 2026-05-21 17:42

from django.db import migrations, models
import django.db.models.deletion
import pendulum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('employees', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('state_or_region', models.CharField(default='', max_length=200)),
                ('zipcode', models.CharField(default='', max_length=11)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0, help_text='Contract value or sale price')),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('garage', models.IntegerField(blank=True, null=True)),
                ('sqft', models.IntegerField(blank=True, null=True)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('land_area_sqft', models.DecimalField(blank=True, decimal_places=2, help_text='Total plot area in sqft (for land/infrastructure projects)', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('sold', 'Sold')], default='available', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('project_date', models.DateTimeField(blank=True, default=pendulum.now)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee')),
                ('photo_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('photo_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('photo_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('photo_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('photo_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('photo_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('photo_main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('service', models.ForeignKey(blank=True, help_text='Which service category this project belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_projects', to='pages.servicedetailpage')),
            ],
        ),
    ]
