# Generated by Django 4.2.30 on 2026-05-22 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Leave blank to use the site default currency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.currency'),
        ),
    ]
