# Generated by Django 4.2.30 on 2026-05-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0006_alter_realtor_hire_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'ordering': ['hire_date']},
        ),
    ]
