# Generated by Django 4.2.30 on 2026-05-21 07:05

from django.db import migrations, models
import domains.realtors.models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0007_alter_realtor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(upload_to=domains.realtors.models.realtor_photo_path),
        ),
    ]
