# Generated by Django 4.0.2 on 2022-04-15 11:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('zipcode', models.CharField(default='', max_length=11)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=1.0, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.IntegerField(default=0)),
                ('lot_size', models.DecimalField(decimal_places=1, default=1.0, max_digits=10)),
                ('is_publised', models.BooleanField(default=True)),
                ('listing_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 11, 11, 56, 595584))),
                ('photo_main', models.ImageField(blank=True, upload_to='media/%Y/%M/%D/')),
                ('photo_1', models.ImageField(blank=True, upload_to='media/%Y/%M/%D/')),
                ('photo_2', models.ImageField(blank=True, upload_to='media/%Y/%M/%D/')),
                ('photo_3', models.ImageField(blank=True, upload_to='media/%Y/%M/%D/')),
                ('photo_4', models.ImageField(blank=True, upload_to='media/%Y/%M/%D/')),
                ('photo_5', models.ImageField(blank=True, upload_to='media/%Y/%M/%D/')),
                ('photo_6', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('realtor', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
