# Generated by Django 4.0.2 on 2022-04-16 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_state_listing_state_or_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_publised',
            new_name='is_published',
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 16, 14, 10, 37, 979348)),
        ),
    ]
