# Generated by Django 4.0.2 on 2022-04-19 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_is_publised_listing_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 19, 16, 23, 48, 86988)),
        ),
    ]
