"""
Django settings for real_estate project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os.path
from os import path
from pathlib import Path

import dj_database_url
from decouple import config, Csv
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())

# Application definition

INSTALLED_APPS = [
    # Django (no django.contrib.admin)
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',

    # Wagtail
    'wagtail',
    'wagtail.admin',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.embeds',
    'wagtailmedia',
    'wagtail.contrib.settings',
    'wagtail.contrib.redirects',
    'wagtail.contrib.routable_page',
    'modelcluster',
    'taggit',

    # Infrastructure apps
    'infrastructure.scripts',

    # Domain apps
    'domains.pages',
    'domains.employees',
    'domains.projects',
    'domains.accounts',
    'domains.inquiries',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'wagtail.contrib.settings.context_processors.settings',
                'domains.pages.context_processors.site_name',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
DB_URL = config('DB_URL', default='')
if DB_URL:
    DATABASES = {
        'default': dj_database_url.parse(DB_URL, conn_max_age=600),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default=5432, cast=int),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    path.join(BASE_DIR, 'static'),
]

STORAGE_BACKEND = config('STORAGE_BACKEND', default='local').lower()

# Far-future cache for hashed assets served by WhiteNoise (local mode).
WHITENOISE_MAX_AGE = 31536000  # 1 year

if STORAGE_BACKEND == 's3':
    # Credentials fall back to the instance IAM role / environment when unset.
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default=None)
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default=None)
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-1')
    AWS_S3_BUCKET_STATIC = config('AWS_S3_BUCKET_STATIC')
    AWS_S3_BUCKET_PUBLIC = config('AWS_S3_BUCKET_PUBLIC')
    # Optional CloudFront / custom domain in front of the public + static buckets.
    AWS_S3_CUSTOM_DOMAIN = config('AWS_S3_CUSTOM_DOMAIN', default=None)

    STORAGES = {
        # Media: Wagtail images & uploaded videos -> public bucket.
        'default': {
            'BACKEND': 'infrastructure.storage.s3_backends.PublicMediaStorage',
        },
        # Collected static assets -> static bucket (hashed + immutable cache).
        'staticfiles': {
            'BACKEND': 'infrastructure.storage.s3_backends.StaticStorage',
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'config.storage.WhiteNoiseStaticFilesStorage',
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# media config
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = 'media/'

# messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

# Wagtail
SITE_NAME = config('SITE_NAME', default='Real Estate')
WAGTAIL_SITE_NAME = SITE_NAME
WAGTAILADMIN_BASE_URL = config('WAGTAILADMIN_BASE_URL', default='http://localhost:8000')
SITE_ID = 1

# email config
EMAIL_PROVIDER = config('EMAIL_PROVIDER', default='django_smtp')  # 'django_smtp' or 'resend'
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@example.com')

# SMTP settings (used when EMAIL_PROVIDER=django_smtp)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Resend settings (used when EMAIL_PROVIDER=resend)
EMAIL_API_KEY = config('EMAIL_API_KEY', default='')

# reCAPTCHA v3
RECAPTCHA_SITE_KEY = config('RECAPTCHA_SITE_KEY', default='')
RECAPTCHA_SECRET_KEY = config('RECAPTCHA_SECRET_KEY', default='')

# Google Maps
MAPS_URL = config('MAPS_URL', default='')
MAPS_EMBED_URL = config('MAPS_EMBED_URL', default='')
