# Generated by Django 4.2.30 on 2026-05-22 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import domains.employees.models
import pendulum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('role', models.CharField(blank=True, help_text='e.g. Project Manager, Site Engineer', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on About page and team highlights')),
                ('hire_date', models.DateTimeField(blank=True, default=pendulum.now)),
                ('photo', models.ImageField(upload_to=domains.employees.models.employee_photo_path)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hire_date'],
            },
        ),
    ]
