# Generated by Django 4.2.30 on 2026-05-21 05:59

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('cta_banner', 5)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('heading', 1), ('subtext', 2), ('button_text', 3), ('button_url', 4)]], {})})),
            ],
            options={
                'verbose_name': 'About Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 2), ('services_row', 8), ('rich_text', 9), ('cta_banner', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Font Awesome icon class, e.g. fa-home'}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('icon', 4), ('title', 0), ('body', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('heading', 3), ('services', 7)]], {}), 9: ('wagtail.blocks.RichTextBlock', (), {}), 10: ('wagtail.blocks.URLBlock', (), {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('button_text', 3), ('button_url', 10)]], {})})),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Real Estate', help_text='Displayed in browser title and footer', max_length=100)),
                ('primary_color', models.CharField(default='#10284e', help_text='Hex color, e.g. #10284e', max_length=7)),
                ('secondary_color', models.CharField(default='#30caa0', help_text='Hex color, e.g. #30caa0', max_length=7)),
                ('phone', models.CharField(blank=True, default='(617)-555-5555', max_length=20)),
                ('email', models.EmailField(blank=True, default='contact@btrealestate.co', max_length=254)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('pinterest_url', models.URLField(blank=True)),
                ('logo', models.ForeignKey(blank=True, help_text='Navbar logo image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Branding & Site Settings',
            },
        ),
    ]
