# Generated by Django 4.2.30 on 2026-05-22 12:58

from django.db import migrations, models
import django.db.models.deletion
import domains.pages.models
import pendulum
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero_banner', 5), ('about_intro', 10), ('mvp_realtor', 12), ('stats_row', 18), ('cta_banner', 20), ('team_section', 22), ('testimonials', 24), ('rich_text', 25)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Override the default hero background image', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('black', 'Black'), ('brand-primary', 'Brand Primary'), ('brand-secondary', 'Brand Secondary')], 'help_text': 'Tint colour of the overlay', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('0.3', 'Light (30%)'), ('0.5', 'Medium (50%)'), ('0.65', 'Dark (65%)'), ('0.85', 'Very Dark (85%)')], 'help_text': 'Opacity of the overlay', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('image', 2), ('overlay_color', 3), ('overlay_opacity', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'We Build More Than Structures'}), 7: ('wagtail.blocks.CharBlock', (), {'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Shown only when no MVP realtor is set', 'required': False}), 9: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('heading', 6), ('lead', 7), ('image', 8), ('body', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Featured Team Member', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('heading', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 200+'}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Projects Completed'}), 15: ('domains.pages.blocks.IconCharBlock', (), {'help_text': 'Font Awesome icon class, e.g. fa-home', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('value', 13), ('label', 14), ('icon', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('heading', 7), ('stats', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative (/contact/) or absolute (https://...) URL', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('button_text', 7), ('button_url', 19)]], {}), 21: ('wagtail.blocks.CharBlock', (), {'default': 'Our Team', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('heading', 21)]], {}), 23: ('wagtail.blocks.IntegerBlock', (), {'default': 4500, 'help_text': 'Slide transition delay in milliseconds (e.g. 4500 = 4.5 s). Set to 0 to disable autoplay.', 'max_value': 20000, 'min_value': 0, 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('heading', 7), ('autoplay_delay', 23)]], {}), 25: ('wagtail.blocks.RichTextBlock', (), {})})),
            ],
            options={
                'verbose_name': 'About Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ColorPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('primary_color', models.CharField(default='#10284e', help_text='Hex color, e.g. #10284e', max_length=7)),
                ('secondary_color', models.CharField(default='#30caa0', help_text='Hex color, e.g. #30caa0', max_length=7)),
            ],
            options={
                'verbose_name': 'Color Preset',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero_banner', 5), ('rich_text', 6), ('faq', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Override the default hero background image', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('black', 'Black'), ('brand-primary', 'Brand Primary'), ('brand-secondary', 'Brand Secondary')], 'help_text': 'Tint colour of the overlay', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('0.3', 'Light (30%)'), ('0.5', 'Medium (50%)'), ('0.65', 'Dark (65%)'), ('0.85', 'Very Dark (85%)')], 'help_text': 'Opacity of the overlay', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('image', 2), ('overlay_color', 3), ('overlay_opacity', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently Asked Questions', 'required': False}), 8: ('wagtail.blocks.TextBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 7), ('items', 10)]], {})})),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 2), ('hero_slideshow', 12), ('services_row', 18), ('rich_text', 19), ('cta_banner', 21), ('stats_row', 27), ('testimonials', 29)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1)]], {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image for this slide'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional overlay caption', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Add at least 3 slides', 'min_num': 3}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('black', 'Black'), ('brand-primary', 'Brand Primary'), ('brand-secondary', 'Brand Secondary')], 'help_text': 'Tint colour of the overlay', 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('0.3', 'Light (30%)'), ('0.5', 'Medium (50%)'), ('0.65', 'Dark (65%)'), ('0.85', 'Very Dark (85%)')], 'help_text': 'Opacity of the overlay', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('slide', 'Slide'), ('fade', 'Fade')], 'help_text': 'Animation style between slides'}), 10: ('wagtail.blocks.IntegerBlock', (), {'default': 5000, 'help_text': 'Milliseconds each slide is shown before transitioning (e.g. 5000 = 5s)'}), 11: ('wagtail.blocks.IntegerBlock', (), {'default': 600, 'help_text': 'Duration of the transition animation in milliseconds'}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('slides', 6), ('overlay_color', 7), ('overlay_opacity', 8), ('transition_type', 9), ('interval', 10), ('animation_speed', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'required': False}), 14: ('domains.pages.blocks.IconCharBlock', (), {}), 15: ('wagtail.blocks.TextBlock', (), {}), 16: ('wagtail.blocks.StructBlock', [[('icon', 14), ('title', 0), ('body', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('heading', 13), ('services', 17), ('overlay_color', 7), ('overlay_opacity', 8)]], {}), 19: ('wagtail.blocks.RichTextBlock', (), {}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative (/contact/) or absolute (https://...) URL', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('button_text', 13), ('button_url', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 200+'}), 23: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Projects Completed'}), 24: ('domains.pages.blocks.IconCharBlock', (), {'help_text': 'Font Awesome icon class, e.g. fa-home', 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('value', 22), ('label', 23), ('icon', 24)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {}), 27: ('wagtail.blocks.StructBlock', [[('heading', 13), ('stats', 26)]], {}), 28: ('wagtail.blocks.IntegerBlock', (), {'default': 4500, 'help_text': 'Slide transition delay in milliseconds (e.g. 4500 = 4.5 s). Set to 0 to disable autoplay.', 'max_value': 20000, 'min_value': 0, 'required': False}), 29: ('wagtail.blocks.StructBlock', [[('heading', 13), ('autoplay_delay', 28)]], {})})),
                ('show_featured_projects', models.BooleanField(default=True, help_text='Toggle the Featured Work section on the home page')),
                ('featured_projects_heading', models.CharField(blank=True, default='Featured Work', help_text='Heading for the Featured Work section', max_length=100)),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero_banner', 5), ('rich_text', 6), ('cta_banner', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Override the default hero background image', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('black', 'Black'), ('brand-primary', 'Brand Primary'), ('brand-secondary', 'Brand Secondary')], 'help_text': 'Tint colour of the overlay', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('0.3', 'Light (30%)'), ('0.5', 'Medium (50%)'), ('0.65', 'Dark (65%)'), ('0.85', 'Very Dark (85%)')], 'help_text': 'Opacity of the overlay', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('image', 2), ('overlay_color', 3), ('overlay_opacity', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative (/contact/) or absolute (https://...) URL', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('button_text', 7), ('button_url', 8)]], {})})),
            ],
            options={
                'verbose_name': 'Projects Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServiceDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero_banner', 5), ('rich_text', 6), ('process_steps', 12), ('gallery', 16), ('projects_grid', 19), ('stats_row', 25), ('testimonials', 27), ('cta_banner', 29)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Override the default hero background image', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('black', 'Black'), ('brand-primary', 'Brand Primary'), ('brand-secondary', 'Brand Secondary')], 'help_text': 'Tint colour of the overlay', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('0.3', 'Light (30%)'), ('0.5', 'Medium (50%)'), ('0.65', 'Dark (65%)'), ('0.85', 'Very Dark (85%)')], 'help_text': 'Opacity of the overlay', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('image', 2), ('overlay_color', 3), ('overlay_opacity', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 01, 02'}), 9: ('wagtail.blocks.TextBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('step_number', 8), ('title', 0), ('body', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 7), ('steps', 11)]], {}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 14: ('wagtail.blocks.StructBlock', [[('image', 13), ('caption', 7)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('heading', 7), ('images', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Our Projects', 'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'No projects in this category yet.', 'help_text': 'Shown when no published projects are linked to this service', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('heading', 17), ('empty_message', 18)]], {}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 200+'}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Projects Completed'}), 22: ('domains.pages.blocks.IconCharBlock', (), {'help_text': 'Font Awesome icon class, e.g. fa-home', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('value', 20), ('label', 21), ('icon', 22)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {}), 25: ('wagtail.blocks.StructBlock', [[('heading', 7), ('stats', 24)]], {}), 26: ('wagtail.blocks.IntegerBlock', (), {'default': 4500, 'help_text': 'Slide transition delay in milliseconds (e.g. 4500 = 4.5 s). Set to 0 to disable autoplay.', 'max_value': 20000, 'min_value': 0, 'required': False}), 27: ('wagtail.blocks.StructBlock', [[('heading', 7), ('autoplay_delay', 26)]], {}), 28: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative (/contact/) or absolute (https://...) URL', 'required': False}), 29: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('button_text', 7), ('button_url', 28)]], {})})),
            ],
            options={
                'verbose_name': 'Service Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero_banner', 5), ('rich_text', 6), ('stats_row', 13), ('testimonials', 15), ('cta_banner', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Override the default hero background image', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('black', 'Black'), ('brand-primary', 'Brand Primary'), ('brand-secondary', 'Brand Secondary')], 'help_text': 'Tint colour of the overlay', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('0.3', 'Light (30%)'), ('0.5', 'Medium (50%)'), ('0.65', 'Dark (65%)'), ('0.85', 'Very Dark (85%)')], 'help_text': 'Opacity of the overlay', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('image', 2), ('overlay_color', 3), ('overlay_opacity', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 200+'}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Projects Completed'}), 10: ('domains.pages.blocks.IconCharBlock', (), {'help_text': 'Font Awesome icon class, e.g. fa-home', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('value', 8), ('label', 9), ('icon', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('heading', 7), ('stats', 12)]], {}), 14: ('wagtail.blocks.IntegerBlock', (), {'default': 4500, 'help_text': 'Slide transition delay in milliseconds (e.g. 4500 = 4.5 s). Set to 0 to disable autoplay.', 'max_value': 20000, 'min_value': 0, 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('heading', 7), ('autoplay_delay', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative (/contact/) or absolute (https://...) URL', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('button_text', 7), ('button_url', 16)]], {})})),
            ],
            options={
                'verbose_name': 'Services Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_role', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=pendulum.now)),
                ('service', models.ForeignKey(blank=True, help_text='Leave blank to show on all service pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='pages.servicedetailpage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('body', wagtail.fields.StreamField([('hero_banner', 5), ('rich_text', 6), ('gallery', 11), ('cta_banner', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Override the default hero background image', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('black', 'Black'), ('brand-primary', 'Brand Primary'), ('brand-secondary', 'Brand Secondary')], 'help_text': 'Tint colour of the overlay', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('0.3', 'Light (30%)'), ('0.5', 'Medium (50%)'), ('0.65', 'Dark (65%)'), ('0.85', 'Very Dark (85%)')], 'help_text': 'Opacity of the overlay', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('image', 2), ('overlay_color', 3), ('overlay_opacity', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('image', 8), ('caption', 7)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 7), ('images', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative (/contact/) or absolute (https://...) URL', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('button_text', 7), ('button_url', 12)]], {})})),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='pages.servicedetailpage')),
            ],
            options={
                'verbose_name': 'Project Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default=domains.pages.models._default_site_name, help_text='Displayed in browser title and footer', max_length=100)),
                ('primary_color', models.CharField(default='#10284e', help_text='Hex color, e.g. #10284e', max_length=7)),
                ('secondary_color', models.CharField(default='#30caa0', help_text='Hex color, e.g. #30caa0', max_length=7)),
                ('phone', models.CharField(blank=True, default='(617)-555-5555', max_length=20)),
                ('email', models.EmailField(blank=True, default='info@site.co', max_length=254)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('pinterest_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('maps_url', models.TextField(blank=True, default='https://maps.app.goo.gl/WXZVF3jKSFmLrGMF9', help_text='Google Maps share link — used for the "Get Directions" button (e.g. https://maps.app.goo.gl/…)')),
                ('maps_embed_url', models.TextField(blank=True, default='https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d451.7493565451374!2d-0.8491877723289881!3d10.788708482747627!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e1!3m2!1sen!2sgh!4v1779392244804!5m2!1sen!2sgh', help_text='Google Maps embed URL for the iframe — get it from Google Maps → Share → Embed a map → copy the iframe src')),
                ('breadcrumb_style', models.CharField(choices=[('bar', 'Context Bar — light strip below nav (default)'), ('overlay', 'Hero Overlay — dark band that flows into the hero')], default='bar', help_text='Controls how breadcrumbs are displayed on interior pages', max_length=10)),
                ('logo', models.ForeignKey(blank=True, help_text='Navbar logo image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Branding & Site Settings',
            },
        ),
        migrations.CreateModel(
            name='BrandingColorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(max_length=7)),
                ('secondary_color', models.CharField(max_length=7)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('branding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_history', to='pages.brandingsettings')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
