# Generated by Django 4.2.30 on 2026-05-21 11:51

from django.db import migrations, models
import django.db.models.deletion
import domains.pages.models
import pendulum
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero_banner', 3), ('about_intro', 8), ('mvp_realtor', 10), ('stats_row', 16), ('cta_banner', 18), ('team_section', 20), ('testimonials', 21), ('rich_text', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Override the default hero background image', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('image', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'We Build More Than Structures'}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Shown only when no MVP realtor is set', 'required': False}), 7: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('heading', 4), ('lead', 5), ('image', 6), ('body', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Featured Team Member', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('heading', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 200+'}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Projects Completed'}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'FA icon class, e.g. fa-home', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('value', 11), ('label', 12), ('icon', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('heading', 5), ('stats', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative (/contact/) or absolute (https://...) URL', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('button_text', 5), ('button_url', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'Our Team', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('heading', 19)]], {}), 21: ('wagtail.blocks.StructBlock', [[('heading', 5)]], {}), 22: ('wagtail.blocks.RichTextBlock', (), {})})),
            ],
            options={
                'verbose_name': 'About Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero_banner', 3), ('rich_text', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Override the default hero background image', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('image', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {})})),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 2), ('services_row', 8), ('rich_text', 9), ('cta_banner', 11), ('stats_row', 17), ('testimonials', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Font Awesome icon class, e.g. fa-home'}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('icon', 4), ('title', 0), ('body', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('heading', 3), ('services', 7)]], {}), 9: ('wagtail.blocks.RichTextBlock', (), {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative (/contact/) or absolute (https://...) URL', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('button_text', 3), ('button_url', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 200+'}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Projects Completed'}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'FA icon class, e.g. fa-home', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('value', 12), ('label', 13), ('icon', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('heading', 3), ('stats', 16)]], {}), 18: ('wagtail.blocks.StructBlock', [[('heading', 3)]], {})})),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero_banner', 3), ('rich_text', 4), ('cta_banner', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Override the default hero background image', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('image', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative (/contact/) or absolute (https://...) URL', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('button_text', 5), ('button_url', 6)]], {})})),
            ],
            options={
                'verbose_name': 'Projects Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServiceDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero_banner', 3), ('rich_text', 4), ('process_steps', 10), ('gallery', 14), ('projects_grid', 17), ('stats_row', 23), ('testimonials', 24), ('cta_banner', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Override the default hero background image', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('image', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 01, 02'}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('step_number', 6), ('title', 0), ('body', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('heading', 5), ('steps', 9)]], {}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 12: ('wagtail.blocks.StructBlock', [[('image', 11), ('caption', 5)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('heading', 5), ('images', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'Our Projects', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'No projects in this category yet.', 'help_text': 'Shown when no published projects are linked to this service', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('heading', 15), ('empty_message', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 200+'}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Projects Completed'}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'FA icon class, e.g. fa-home', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('value', 18), ('label', 19), ('icon', 20)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {}), 23: ('wagtail.blocks.StructBlock', [[('heading', 5), ('stats', 22)]], {}), 24: ('wagtail.blocks.StructBlock', [[('heading', 5)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative (/contact/) or absolute (https://...) URL', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('button_text', 5), ('button_url', 25)]], {})})),
            ],
            options={
                'verbose_name': 'Service Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero_banner', 3), ('rich_text', 4), ('stats_row', 11), ('testimonials', 12), ('cta_banner', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Override the default hero background image', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('image', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 200+'}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Projects Completed'}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'FA icon class, e.g. fa-home', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('value', 6), ('label', 7), ('icon', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 5), ('stats', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 5)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative (/contact/) or absolute (https://...) URL', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('button_text', 5), ('button_url', 13)]], {})})),
            ],
            options={
                'verbose_name': 'Services Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_role', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=pendulum.now)),
                ('author_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('service', models.ForeignKey(blank=True, help_text='Leave blank to show on all service pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='pages.servicedetailpage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('body', wagtail.fields.StreamField([('hero_banner', 3), ('rich_text', 4), ('gallery', 9), ('cta_banner', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Override the default hero background image', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('image', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('image', 6), ('caption', 5)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('heading', 5), ('images', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative (/contact/) or absolute (https://...) URL', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('button_text', 5), ('button_url', 10)]], {})})),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='pages.servicedetailpage')),
            ],
            options={
                'verbose_name': 'Project Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default=domains.pages.models._default_site_name, help_text='Displayed in browser title and footer', max_length=100)),
                ('primary_color', models.CharField(default='#10284e', help_text='Hex color, e.g. #10284e', max_length=7)),
                ('secondary_color', models.CharField(default='#30caa0', help_text='Hex color, e.g. #30caa0', max_length=7)),
                ('phone', models.CharField(blank=True, default='(617)-555-5555', max_length=20)),
                ('email', models.EmailField(blank=True, default='info@site.co', max_length=254)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('pinterest_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('logo', models.ForeignKey(blank=True, help_text='Navbar logo image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Branding & Site Settings',
            },
        ),
    ]
