# Generated by Django 4.2.30 on 2026-05-21 06:26

from django.db import migrations, models
import domains.pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingsettings',
            name='site_name',
            field=models.CharField(default=domains.pages.models._default_site_name, help_text='Displayed in browser title and footer', max_length=100),
        ),
    ]
