# Generated by Django 4.2.30 on 2026-05-21 13:44

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_projects_heading',
            field=models.CharField(blank=True, default='Featured Work', help_text='Heading for the Featured Work section', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_featured_projects',
            field=models.BooleanField(default=True, help_text='Toggle the Featured Work section on the home page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 2), ('hero_slideshow', 10), ('services_row', 16), ('rich_text', 17), ('cta_banner', 19), ('stats_row', 25), ('testimonials', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1)]], {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image for this slide'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional overlay caption', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Add at least 3 slides', 'min_num': 3}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('slide', 'Slide'), ('fade', 'Fade')], 'help_text': 'Animation style between slides'}), 8: ('wagtail.blocks.IntegerBlock', (), {'default': 5000, 'help_text': 'Milliseconds each slide is shown before transitioning (e.g. 5000 = 5s)'}), 9: ('wagtail.blocks.IntegerBlock', (), {'default': 600, 'help_text': 'Duration of the transition animation in milliseconds'}), 10: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('slides', 6), ('transition_type', 7), ('interval', 8), ('animation_speed', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Font Awesome icon class, e.g. fa-home'}), 13: ('wagtail.blocks.TextBlock', (), {}), 14: ('wagtail.blocks.StructBlock', [[('icon', 12), ('title', 0), ('body', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('heading', 11), ('services', 15)]], {}), 17: ('wagtail.blocks.RichTextBlock', (), {}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative (/contact/) or absolute (https://...) URL', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('button_text', 11), ('button_url', 18)]], {}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 200+'}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Projects Completed'}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'FA icon class, e.g. fa-home', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('value', 20), ('label', 21), ('icon', 22)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {}), 25: ('wagtail.blocks.StructBlock', [[('heading', 11), ('stats', 24)]], {}), 26: ('wagtail.blocks.StructBlock', [[('heading', 11)]], {})}),
        ),
    ]
