# Generated by Django 4.2.30 on 2026-05-21 19:06

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='body',
            field=wagtail.fields.StreamField([('hero_banner', 5), ('rich_text', 6), ('faq', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Override the default hero background image', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('black', 'Black'), ('brand-primary', 'Brand Primary'), ('brand-secondary', 'Brand Secondary')], 'help_text': 'Tint colour of the overlay', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('0.3', 'Light (30%)'), ('0.5', 'Medium (50%)'), ('0.65', 'Dark (65%)'), ('0.85', 'Very Dark (85%)')], 'help_text': 'Opacity of the overlay', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('image', 2), ('overlay_color', 3), ('overlay_opacity', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently Asked Questions', 'required': False}), 8: ('wagtail.blocks.TextBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 7), ('items', 10)]], {})}),
        ),
    ]
