# Generated by Django 4.2.30 on 2026-05-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_brandingsettings_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='project_related_count',
            field=models.PositiveSmallIntegerField(default=3, help_text='Number of related projects to display (max 6)'),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='project_show_related',
            field=models.BooleanField(default=True, help_text='Show a "More Projects" section at the bottom of each project page'),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='project_show_stats_bar',
            field=models.BooleanField(default=True, help_text='Show the key stats strip (price, sqft, beds, baths) on the project detail page'),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='project_sold_message',
            field=models.CharField(blank=True, default='This project is complete.', help_text='Heading shown when a project has been sold', max_length=200),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='project_sticky_cta',
            field=models.BooleanField(default=True, help_text='Keep the "Make An Inquiry" button visible while scrolling on desktop; show a fixed bottom bar on mobile'),
        ),
    ]
