# Generated by Django 4.2.30 on 2026-05-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_brandingsettings_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='email',
            field=models.EmailField(blank=True, default='info@site.co', max_length=254),
        ),
    ]
