# Generated by Django 4.2.30 on 2026-05-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_contactpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='maps_url',
            field=models.URLField(blank=True, default='https://maps.app.goo.gl/WXZVF3jKSFmLrGMF9', help_text='Google Maps share link for your location (e.g. https://maps.app.goo.gl/…)'),
        ),
    ]
