# Generated by Django 4.2.30 on 2026-05-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_project_detail_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
