# Generated by Django 4.2.30 on 2026-05-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_brandingsettings_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='maps_embed_url',
            field=models.TextField(blank=True, default='https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d451.7493565451374!2d-0.8491877723289881!3d10.788708482747627!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e1!3m2!1sen!2sgh!4v1779392244804!5m2!1sen!2sgh', help_text='Google Maps embed URL for the iframe — get it from Google Maps → Share → Embed a map → copy the iframe src'),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='maps_url',
            field=models.TextField(blank=True, default='https://maps.app.goo.gl/WXZVF3jKSFmLrGMF9', help_text='Google Maps share link — used for the "Get Directions" button (e.g. https://maps.app.goo.gl/…)'),
        ),
    ]
