# Generated by Django 4.2.30 on 2026-05-21 07:28

from django.db import migrations, models
import django.db.models.deletion
import pendulum
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('pages', '0003_add_tiktok_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero_banner', 2), ('rich_text', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {})})),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero_banner', 2), ('rich_text', 3), ('cta_banner', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('button_text', 4), ('button_url', 5)]], {})})),
            ],
            options={
                'verbose_name': 'Projects Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServiceDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero_banner', 2), ('rich_text', 3), ('process_steps', 9), ('gallery', 13), ('stats_row', 19), ('testimonials', 20), ('cta_banner', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 01, 02'}), 6: ('wagtail.blocks.TextBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('step_number', 5), ('title', 0), ('body', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('heading', 4), ('steps', 8)]], {}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 11: ('wagtail.blocks.StructBlock', [[('image', 10), ('caption', 4)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('heading', 4), ('images', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 200+'}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Projects Completed'}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'FA icon class, e.g. fa-home', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('value', 14), ('label', 15), ('icon', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('heading', 4), ('stats', 18)]], {}), 20: ('wagtail.blocks.StructBlock', [[('heading', 4)]], {}), 21: ('wagtail.blocks.URLBlock', (), {'required': False}), 22: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('button_text', 4), ('button_url', 21)]], {})})),
            ],
            options={
                'verbose_name': 'Service Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero_banner', 2), ('rich_text', 3), ('stats_row', 10), ('testimonials', 11), ('cta_banner', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 200+'}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Projects Completed'}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'FA icon class, e.g. fa-home', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('value', 5), ('label', 6), ('icon', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('heading', 4), ('stats', 9)]], {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 4)]], {}), 12: ('wagtail.blocks.URLBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('button_text', 4), ('button_url', 12)]], {})})),
            ],
            options={
                'verbose_name': 'Services Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 2), ('services_row', 8), ('rich_text', 9), ('cta_banner', 11), ('stats_row', 17), ('testimonials', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Font Awesome icon class, e.g. fa-home'}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('icon', 4), ('title', 0), ('body', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('heading', 3), ('services', 7)]], {}), 9: ('wagtail.blocks.RichTextBlock', (), {}), 10: ('wagtail.blocks.URLBlock', (), {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subtext', 1), ('button_text', 3), ('button_url', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 200+'}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Projects Completed'}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'FA icon class, e.g. fa-home', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('value', 12), ('label', 13), ('icon', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('heading', 3), ('stats', 16)]], {}), 18: ('wagtail.blocks.StructBlock', [[('heading', 3)]], {})}),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_role', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=pendulum.now)),
                ('author_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('service', models.ForeignKey(blank=True, help_text='Leave blank to show on all service pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='pages.servicedetailpage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('gallery', 5), ('cta_banner', 9)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 1)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('heading', 1), ('images', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.blocks.TextBlock', (), {'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('heading', 6), ('subtext', 7), ('button_text', 1), ('button_url', 8)]], {})})),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='pages.servicedetailpage')),
            ],
            options={
                'verbose_name': 'Project Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
