# Generated by Django 4.2.30 on 2026-05-21 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_brandingsettings_maps_embed_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='author_photo',
        ),
    ]
