# Generated by Django 4.2.30 on 2026-05-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_color_preset_and_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='breadcrumb_style',
            field=models.CharField(choices=[('bar', 'Context Bar — light strip below nav (default)'), ('overlay', 'Hero Overlay — dark band that flows into the hero')], default='bar', help_text='Controls how breadcrumbs are displayed on interior pages', max_length=10),
        ),
    ]
