# Generated by Django 4.2.30 on 2026-05-22 12:58

from django.db import migrations, models
import django.db.models.deletion
import pendulum
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('service', models.CharField(blank=True, help_text='Service the person is interested in', max_length=200)),
                ('message', wagtail.fields.RichTextField(blank=True)),
                ('timestamp', models.DateTimeField(default=pendulum.now)),
            ],
            options={
                'verbose_name': 'General Inquiry',
                'verbose_name_plural': 'General Inquiries',
                'db_table': 'contacts_generalinquiry',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('message', wagtail.fields.RichTextField(blank=True)),
                ('timestamp', models.DateTimeField(default=pendulum.now)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Project Inquiry',
                'verbose_name_plural': 'Project Inquiries',
                'db_table': 'contacts_contact',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_inquiry_subject', models.CharField(default='Thank you for your inquiry', help_text='Subject line for project inquiry confirmation emails', max_length=200)),
                ('project_inquiry_intro', models.TextField(default='Thank you for reaching out about {project}. We have received your inquiry and will be in touch shortly.', help_text='Intro paragraph. Use {project} to insert the project name.')),
                ('general_inquiry_subject', models.CharField(default='We received your message', help_text='Subject line for general contact form confirmation emails', max_length=200)),
                ('general_inquiry_intro', models.TextField(default='Thank you for contacting us, {name}. We have received your message and will be in touch shortly.', help_text="Intro paragraph. Use {name} to insert the sender's name.")),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Email Settings',
            },
        ),
    ]
