# Generated by Django 4.2.30 on 2026-05-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
