# Generated by Django 4.2.30 on 2026-05-21 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_inquiry_subject', models.CharField(default='Thank you for your inquiry', help_text='Subject line for project inquiry confirmation emails', max_length=200)),
                ('project_inquiry_intro', models.TextField(default='Thank you for reaching out about {project}. We have received your inquiry and will be in touch shortly.', help_text='Intro paragraph. Use {project} to insert the project name.')),
                ('general_inquiry_subject', models.CharField(default='We received your message', help_text='Subject line for general contact form confirmation emails', max_length=200)),
                ('general_inquiry_intro', models.TextField(default='Thank you for contacting us, {name}. We have received your message and will be in touch shortly.', help_text="Intro paragraph. Use {name} to insert the sender's name.")),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Email Settings',
            },
        ),
    ]
