# Generated by Django 4.2.30 on 2026-05-21 18:49

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_emailsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinquiry',
            name='message',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectinquiry',
            name='message',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
