# Generated by Django 4.0.2 on 2022-04-15 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('is_mvp', models.BooleanField(default=False)),
                ('hire_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 11, 11, 56, 594584))),
                ('photo', models.ImageField(upload_to='media/%Y/%m/%d/')),
            ],
        ),
    ]
